apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==    # base64 for "root"
  MYSQL_PASSWORD: cm9vdA==         # base64 for "root"
                                   # echo -n "root" | base64
